FROM --platform=linux/amd64 public.ecr.aws/lambda/python:3.11

WORKDIR /var/task

COPY ./app ${LAMBDA_TASK_ROOT}/

RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

CMD ["start_lambda.handler"]